language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t vladhondru25/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vladhondru25/react-test npm test

after_success:
    - docker build -t vladhondru25/multi-client ./client
    - docker build -t vladhondru25/multi-nginx ./nginx
    - docker build -t vladhondru25/multi-server ./server
    - docker build -t vladhondru25/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push vladhondru25/multi-client
    - docker push vladhondru25/multi-nginx
    - docker push vladhondru25/multi-server
    - docker push vladhondru25/multi-worker
